spring:
  application:
    name: recursify
  datasource:
    # Connection string for your database
    url: jdbc:mysql://localhost:3306/recursifydb?useSSL=false&serverTimezone=UTC
    # Default MySQL username is usually 'root'
    username: root
    # Replace with your actual MySQL password
    password: Mssql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 'update' will create/update tables automatically based on your Java entities
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
